# Generated by Django 5.2.8 on 2025-11-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(help_text='Grade/Year (e.g., 11, 12, 1st Year, 2nd Year, Final Year, B.Sc, etc.)', max_length=50),
        ),
    ]
