# Generated by Django 5.2.8 on 2025-11-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject_type', models.CharField(choices=[('hadiya', 'Hadiya (Islamic)'), ('division', 'Division Specific')], max_length=20)),
                ('grade', models.CharField(help_text='Grade/Year this subject belongs to', max_length=50)),
                ('code', models.CharField(blank=True, help_text='Subject code', max_length=20)),
                ('max_marks', models.PositiveIntegerField(default=100, help_text='Maximum marks for this subject')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(blank=True, help_text='Required for division-specific subjects, leave blank for Hadiya', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.division')),
            ],
            options={
                'ordering': ['grade', 'subject_type', 'name'],
                'unique_together': {('name', 'grade', 'division', 'subject_type')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.examtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='students.student')),
            ],
            options={
                'ordering': ['-generated_at', 'student'],
                'unique_together': {('student', 'exam_type', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('entered_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.examtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'ordering': ['-exam_date', 'student', 'subject'],
                'indexes': [models.Index(fields=['student', 'exam_type'], name='students_ma_student_1f81fa_idx'), models.Index(fields=['exam_type', 'subject'], name='students_ma_exam_ty_c9840b_idx')],
                'unique_together': {('student', 'exam_type', 'subject')},
            },
        ),
    ]
