# Generated by Django 5.2.8 on 2026-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_examtype_subject_progressreport_markentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("is_optional", models.BooleanField(default=False)),
            ],
        ),
    ]
