# Generated by Django 5.2.11 on 2026-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='subject_type',
            field=models.CharField(choices=[('all', 'All Subjects'), ('hadiya', 'Hadiya (Islamic)'), ('division', 'Division Specific')], default='all', help_text='Filter subjects shown during mark entry for this exam', max_length=20),
        ),
    ]
