# Generated by Django 5.2.8 on 2026-03-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_examtype_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '2024-2025'", max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one academic year should be active at a time.')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'enrollment', 'student']},
        ),
        migrations.AlterModelOptions(
            name='markentry',
            options={'ordering': ['-exam_date', 'enrollment', 'student', 'subject']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/Year (e.g., 11, 12, 1st Year, 2nd Year, Final Year, B.Sc, etc.)', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='Grade/Year for this session (e.g., 11, 12, 1st Year)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.academicyear')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.division')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year__name', 'grade', 'division', 'student__last_name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='markentry',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='students.enrollment'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date'], name='students_at_enrollm_3ba727_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date', 'attendance_type'], name='students_at_enrollm_c9614d_idx'),
        ),
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['enrollment', 'exam_type'], name='students_ma_enrollm_556ee7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
