# Generated by Django 5.2.8 on 2026-03-01 11:09

from django.db import migrations

def create_initial_enrollments(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    AcademicYear = apps.get_model('students', 'AcademicYear')
    Enrollment = apps.get_model('students', 'Enrollment')
    Attendance = apps.get_model('students', 'Attendance')
    MarkEntry = apps.get_model('students', 'MarkEntry')
    ProgressReport = apps.get_model('students', 'ProgressReport')

    # 1. Create default academic year
    active_year, created = AcademicYear.objects.get_or_create(
        name='2024-2025',
        defaults={'is_active': True}
    )

    # 2. Iterate and create Enrollments using old Student fields
    for student in Student.objects.all():
        enrollment, enc_created = Enrollment.objects.get_or_create(
            student=student,
            academic_year=active_year,
            defaults={
                'grade': student.grade or 'Unknown',
                'division': student.division,
                'room': student.room,
            }
        )
        
        # 3. Link old records to this new enrollment based on the student
        Attendance.objects.filter(student=student, enrollment__isnull=True).update(enrollment=enrollment)
        MarkEntry.objects.filter(student=student, enrollment__isnull=True).update(enrollment=enrollment)
        ProgressReport.objects.filter(student=student, enrollment__isnull=True).update(enrollment=enrollment)

def reverse_initial_enrollments(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_academicyear_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_enrollments, reverse_initial_enrollments),
    ]
