# Generated by Django 5.2.8 on 2026-03-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_create_academic_year_enrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='division',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='markentry',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='students.enrollment'),
        ),
    ]
