# Generated by Django 5.2.8 on 2026-03-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_section_alter_academicyear_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.section'),
        ),
    ]
