# Generated by Django 5.2.8 on 2026-03-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_enrollment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.section'),
        ),
    ]
