# Generated by Django 5.2.8 on 2026-03-07 06:01

from django.db import migrations

import django.db.models.deletion
from django.db import migrations, models

def copy_grades(apps, schema_editor):
    Enrollment = apps.get_model('students', 'Enrollment')
    Subject = apps.get_model('students', 'Subject')
    Grade = apps.get_model('students', 'Grade')
    
    # Process Enrollments
    for enrollment in Enrollment.objects.all():
        if enrollment.grade:
            grade_obj, _ = Grade.objects.get_or_create(name=enrollment.grade, defaults={'order': 0, 'section': enrollment.section})
            enrollment.grade_fk = grade_obj
            enrollment.save()
            
    # Process Subjects
    for subject in Subject.objects.all():
        if subject.grade:
            grade_obj, _ = Grade.objects.get_or_create(name=subject.grade, defaults={'order': 0, 'section': subject.section})
            subject.grade_fk = grade_obj
            subject.save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_enquiry_academic_year_enquiry_section'),
    ]

    operations = [
        # 1. Create Grade model
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display sorting')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='students.section')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        
        # 2. Add temp foreign key fields
        migrations.AddField(
            model_name='enrollment',
            name='grade_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='students.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.grade'),
        ),
        
        # 3. Data Migration
        migrations.RunPython(copy_grades, reverse_code=migrations.RunPython.noop),
        
        # 4. Remove old char fields
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        
        # 5. Rename new fk fields to 'grade'
        migrations.RenameField(
            model_name='enrollment',
            old_name='grade_fk',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='grade_fk',
            new_name='grade',
        ),
        
        # 6. Re-add unique constraints
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade', 'division', 'subject_type')},
        ),
    ]
