# Generated by Django 5.2.8 on 2026-03-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='application_number',
            field=models.CharField(blank=True, help_text='Auto-generated application number', max_length=50, null=True, unique=True),
        ),
    ]
