# Generated by Django 5.2.8 on 2026-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_enquiry_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
