# Generated by Django 5.2.8 on 2026-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_siblings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Application Received'), ('Token Generated', 'Token Generated'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
