# Generated by Django 5.2.8 on 2026-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for the interview', null=True),
        ),
    ]
