# Generated by Django 5.2.8 on 2026-03-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_enquiry_interview_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_interview_date', models.DateTimeField(blank=True, help_text='Common date and time for all interviews', null=True)),
            ],
        ),
    ]
