# Generated by Django 5.2.8 on 2026-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_message_template',
            field=models.TextField(default='We have received your application. Your application number is {app_no}. You can check your application status directly by clicking this link: {status_link}', help_text='Available placeholders: {name}, {app_no}, {status_link}'),
        ),
    ]
