# Generated by Django 5.2.8 on 2026-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_globalsettings_whatsapp_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
