# Generated by Django 5.2.8 on 2026-03-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_studentfee_billing_month_and_more'),
        ('students', '0021_student_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='fees.busstop'),
        ),
    ]
