# Generated by Django 5.2.8 on 2026-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_jobopening_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
