# Generated by Django 5.2.8 on 2026-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_jobapplication_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Landing Page Stats',
            },
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
