# Generated by Django 5.2.8 on 2026-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_landingpagestats_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Designates whether the exam results are visible to students.'),
        ),
    ]
