# Generated by Django 5.2.8 on 2026-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_examtype_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uses_bus',
            field=models.BooleanField(default=False, help_text='Designates whether the student uses institutional transport'),
        ),
    ]
