# Generated by Django 5.2.8 on 2026-06-15 04:24

from django.db import migrations

def clean_phones(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for s in Student.objects.filter(phone__endswith='.0'):
        s.phone = s.phone[:-2]
        s.save(update_fields=['phone'])
        
    Enquiry = apps.get_model('students', 'Enquiry')
    for e in Enquiry.objects.filter(phone__endswith='.0'):
        e.phone = e.phone[:-2]
        e.save(update_fields=['phone'])

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_merge_20260611_1907'),
    ]

    operations = [
        migrations.RunPython(clean_phones),
    ]
