# Generated by Django 5.2.8 on 2026-06-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_clean_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.TextField(help_text='128-dimensional face embedding array as JSON string')),
                ('photo', models.TextField(blank=True, help_text='Base64 encoded cropped face snapshot image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Face Profile',
                'verbose_name_plural': 'Student Face Profiles',
            },
        ),
    ]
