# Generated by Django 5.2.4 on 2026-07-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_studentface'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectMaxMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.PositiveIntegerField(default=100, help_text='Maximum marks for this subject in this exam')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_max_marks', to='students.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_max_marks', to='students.subject')),
            ],
            options={
                'verbose_name': 'Exam Subject Max Mark',
                'verbose_name_plural': 'Exam Subject Max Marks',
                'ordering': ['exam_type', 'subject__grade', 'subject__name'],
                'unique_together': {('exam_type', 'subject')},
            },
        ),
    ]
