# Generated by Django 5.2.4 on 2026-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_exam_subject_max_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Specific subjects allowed for this exam. If none selected, all matching subjects are allowed.', related_name='exam_types', to='students.subject'),
        ),
    ]
