# Generated by Django 5.2.4 on 2026-07-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_add_exam_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_password',
            field=models.CharField(blank=True, help_text='Stored password for reference by Admin', max_length=128, null=True),
        ),
    ]
