# Generated by Django 5.2.4 on 2026-07-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_userprofile_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='suspend_student_fees',
            field=models.BooleanField(default=False, help_text='Suspend student portal fee section for maintenance'),
        ),
    ]
