# Generated by Django 5.2.4 on 2026-07-21 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_globalsettings_suspend_student_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General Notice'), ('academic', 'Academic & Classes'), ('exam', 'Examinations & Results'), ('fees', 'Fee & Accounts'), ('holiday', 'Holiday & Campus Closure'), ('event', 'Events & Functions'), ('hostel', 'Hostel & Mess'), ('urgent', 'Urgent Alert')], default='general', max_length=30)),
                ('audience', models.CharField(choices=[('all', 'Everyone (Students & Staff)'), ('students', 'Students Only'), ('teachers', 'Teachers & Staff Only'), ('hostel', 'Hostel Residents Only')], default='all', max_length=30)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of student dashboard')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
