# Generated by Django 5.2.4 on 2026-07-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_campusannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='grades',
            field=models.ManyToManyField(blank=True, help_text='Specific classes/grades. Leave empty to apply to ALL classes.', related_name='holidays', to='students.grade'),
        ),
        migrations.DeleteModel(
            name='CampusAnnouncement',
        ),
    ]
