# Generated by Django 5.2.4 on 2026-07-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_holiday_grades_delete_campusannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='session_start_date',
            field=models.DateField(blank=True, help_text='Optional class start date for academic session (e.g. June 15)', null=True),
        ),
    ]
