# Generated by Django 5.2.4 on 2026-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_grade_session_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label or title for admin reference', max_length=200)),
                ('content', models.TextField(help_text='The announcement text displayed in the landing page ticker')),
                ('icon', models.CharField(blank=True, default='🚀', help_text='Emoji or icon (e.g. 📢, 🏆, ✨, 📱)', max_length=50)),
                ('link', models.CharField(blank=True, help_text='Optional URL link (e.g. /results/ or https://...)', max_length=500)),
                ('text_color', models.CharField(default='#25D366', help_text='Text highlight color code (e.g. #25D366, #f1c40f)', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide this ticker on the landing page')),
                ('order', models.IntegerField(default=0, help_text='Order index (lower values appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Ticker Item',
                'verbose_name_plural': 'News Ticker Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
