# Generated by Django 5.2.4 on 2026-07-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_periodtiming_teachersubjectassignment_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_common_subject',
            field=models.BooleanField(default=False, help_text='Is this subject taught jointly across multiple divisions/classes?'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='combined_group_id',
            field=models.CharField(blank=True, help_text='Group tag linking simultaneous combined slots', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='Is this a joint/combined class period shared across divisions?'),
        ),
    ]
