# Generated by Django 5.2.4 on 2026-08-19 06:41

import django.db.models.deletion
from django.db import migrations, models


def migrate_divisions_to_grades(apps, schema_editor):
    Division = apps.get_model('students', 'Division')
    Enrollment = apps.get_model('students', 'Enrollment')
    Subject = apps.get_model('students', 'Subject')
    TeacherSubjectAssignment = apps.get_model('students', 'TeacherSubjectAssignment')
    TimetableSlot = apps.get_model('students', 'TimetableSlot')
    
    try:
        FeeStructure = apps.get_model('fees', 'FeeStructure')
    except Exception:
        FeeStructure = None

    def get_or_clone_division(grade_id, div_id):
        if not grade_id or not div_id:
            return div_id
        
        try:
            div = Division.objects.get(id=div_id)
        except Division.DoesNotExist:
            return div_id

        if div.grade_id is None:
            div.grade_id = grade_id
            div.save()
            return div.id
        
        if div.grade_id == grade_id:
            return div.id
        
        existing_clone = Division.objects.filter(grade_id=grade_id, name=div.name).first()
        if existing_clone:
            return existing_clone.id
        
        new_div = Division.objects.create(
            name=div.name,
            grade_id=grade_id,
            section_id=div.section_id,
            description=div.description
        )
        return new_div.id

    # 1. Enrollments
    enrollment_combos = list(
        Enrollment.objects.filter(grade__isnull=False, division__isnull=False)
        .values_list('grade_id', 'division_id')
        .distinct()
    )
    for g_id, d_id in enrollment_combos:
        target_d_id = get_or_clone_division(g_id, d_id)
        if target_d_id != d_id:
            Enrollment.objects.filter(grade_id=g_id, division_id=d_id).update(division_id=target_d_id)

    # 2. Subjects
    subject_combos = list(
        Subject.objects.filter(grade__isnull=False, division__isnull=False)
        .values_list('grade_id', 'division_id')
        .distinct()
    )
    for g_id, d_id in subject_combos:
        target_d_id = get_or_clone_division(g_id, d_id)
        if target_d_id != d_id:
            Subject.objects.filter(grade_id=g_id, division_id=d_id).update(division_id=target_d_id)

    # 3. TeacherSubjectAssignments
    tsa_combos = list(
        TeacherSubjectAssignment.objects.filter(grade__isnull=False, division__isnull=False)
        .values_list('grade_id', 'division_id')
        .distinct()
    )
    for g_id, d_id in tsa_combos:
        target_d_id = get_or_clone_division(g_id, d_id)
        if target_d_id != d_id:
            TeacherSubjectAssignment.objects.filter(grade_id=g_id, division_id=d_id).update(division_id=target_d_id)

    # 4. TimetableSlots
    slot_combos = list(
        TimetableSlot.objects.filter(grade__isnull=False, division__isnull=False)
        .values_list('grade_id', 'division_id')
        .distinct()
    )
    for g_id, d_id in slot_combos:
        target_d_id = get_or_clone_division(g_id, d_id)
        if target_d_id != d_id:
            TimetableSlot.objects.filter(grade_id=g_id, division_id=d_id).update(division_id=target_d_id)

    # 5. FeeStructures
    if FeeStructure:
        fee_combos = list(
            FeeStructure.objects.filter(grade__isnull=False, division__isnull=False)
            .values_list('grade_id', 'division_id')
            .distinct()
        )
        for g_id, d_id in fee_combos:
            target_d_id = get_or_clone_division(g_id, d_id)
            if target_d_id != d_id:
                FeeStructure.objects.filter(grade_id=g_id, division_id=d_id).update(division_id=target_d_id)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_subject_is_common_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['grade', 'name']},
        ),
        migrations.AddField(
            model_name='division',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='students.grade'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(migrate_divisions_to_grades, reverse_code=reverse_migration),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('grade', 'name')},
        ),
    ]
