# Generated by Django 5.2.4 on 2026-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_connect_grade_and_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='markentry',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
