# Generated by Django 5.2.4 on 2026-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_markentry_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubjectmaxmark',
            name='pass_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Passing marks for this subject in this exam (overrides Subject.pass_marks)', null=True),
        ),
        migrations.AddField(
            model_name='markentry',
            name='pass_marks',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.PositiveIntegerField(default=30, help_text='Minimum passing marks for this subject'),
        ),
    ]
