# Generated by Django 5.2.4 on 2026-09-29 02:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_examsubjectmaxmark_pass_marks_markentry_pass_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('time_slot', models.CharField(blank=True, help_text='e.g. 05:30 AM or 08:30 PM - 10:00 PM', max_length=100)),
                ('icon', models.CharField(blank=True, default='fa-calendar-check', help_text='FontAwesome icon name e.g. fa-mosque, fa-book-open, fa-moon, fa-sun, fa-bed, fa-utensils', max_length=50)),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Accent color hex e.g. #6366f1, #10b981, #f59e0b, #ec4899, #8b5cf6', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for button display')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this activity is active for attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel Activity',
                'verbose_name_plural': 'Hostel Activities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused / Away')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('marked_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.hostelactivity')),
                ('student', models.ForeignKey(limit_choices_to={'student_type': 'hostel'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Attendance',
                'verbose_name_plural': 'Hostel Attendances',
                'ordering': ['-date', 'activity__order', 'student__last_name'],
                'indexes': [models.Index(fields=['student', 'date'], name='students_ho_student_d3c24d_idx'), models.Index(fields=['activity', 'date'], name='students_ho_activit_7e3945_idx'), models.Index(fields=['date', 'status'], name='students_ho_date_7f5a52_idx')],
                'unique_together': {('student', 'activity', 'date')},
            },
        ),
    ]
