# Generated by Django 5.2.4 on 2026-09-29 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_hostelactivity_hostelattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelmovement',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hostelmovement',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hostelmovement',
            name='escorting_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostelmovement',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hostelmovement',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hostelmovement',
            name='sign',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
