# Generated by Django 5.2.8 on 2026-01-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0003_examtype_subject_progressreport_markentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.division",
                    ),
                ),
            ],
        ),
    ]
