# Generated by Django 5.2.8 on 2026-01-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0002_alter_alumniregistration_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumniregistration",
            options={},
        ),
    ]
