# Generated by Django 5.2.8 on 2026-02-21 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_examtype_subject_progressreport_markentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['stop_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 1st Installment, 2nd Installment', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_refundable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='fees.feecategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('due', 'Due'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='due', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.feeitem')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.courseinstallment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', 'status'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('card', 'Card')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID/Cheque No.', max_length=100)),
                ('collected_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
