# Generated by Django 5.2.8 on 2026-02-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_accountcategory_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='income',
            field=models.ForeignKey(blank=True, help_text='The overarching Income record this payment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='fees.income'),
        ),
    ]
