# Generated by Django 5.2.8 on 2026-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_feestructure'),
        ('students', '0020_globalsettings_whatsapp_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='applicable_divisions',
            field=models.ManyToManyField(blank=True, help_text='If none selected, applies to all divisions.', related_name='applicable_fees', to='students.division'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='applicable_grades',
            field=models.ManyToManyField(blank=True, help_text='If none selected, applies to all grades.', related_name='applicable_fees', to='students.grade'),
        ),
    ]
