# Generated by Django 5.2.8 on 2026-03-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feeitem_applicable_divisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='target_student_type',
            field=models.CharField(choices=[('all', 'All Students'), ('hostel', 'Hostel Students Only'), ('day_scholar', 'Day Scholars Only')], default='all', max_length=20),
        ),
    ]
