# Generated by Django 5.2.8 on 2026-03-15 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feeitem_target_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='is_monthly',
            field=models.BooleanField(default=False, help_text='Generation happens 1st of every month (e.g., Hostel/Vehicle)'),
        ),
        migrations.CreateModel(
            name='FeeInstallmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('name', models.CharField(help_text='e.g., 1st Installment', max_length=100)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this specific installment', max_digits=10)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_templates', to='fees.feeitem')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('fee_item', 'installment_number')},
            },
        ),
    ]
