# Generated by Django 5.2.8 on 2026-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_feeitem_is_monthly_feeinstallmenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='billing_month',
            field=models.DateField(blank=True, help_text='The month this recurring fee covers', null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='concession_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='concession_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='prorated_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='e.g., 40, 80, 100', max_digits=5),
        ),
    ]
