# Generated by Django 5.2.8 on 2026-03-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_studentfee_billing_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcategory',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic'), ('hostel', 'Hostel'), ('general', 'General/Institutional')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic'), ('hostel', 'Hostel'), ('general', 'General/Institutional')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic'), ('hostel', 'Hostel'), ('general', 'General/Institutional')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic'), ('hostel', 'Hostel'), ('general', 'General/Institutional')], default='academic', help_text='The department this fee belongs to (Academic vs Hostel)', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic'), ('hostel', 'Hostel'), ('general', 'General/Institutional')], default='general', max_length=20),
        ),
    ]
