# Generated by Django 5.2.8 on 2026-03-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_accountcategory_department_expense_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='present_days',
            field=models.PositiveIntegerField(blank=True, help_text='Manual adjustment of days present in the billing month', null=True),
        ),
    ]
