# Generated by Django 5.2.8 on 2026-04-19 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_studentfee_present_days'),
        ('students', '0022_student_bus_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total sum received from student', max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('card', 'Card')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('collected_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transactions', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_transaction',
            field=models.ForeignKey(blank=True, help_text='The unified transaction this payment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='fees.receipttransaction'),
        ),
    ]
