# Generated by Django 5.2.8 on 2026-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_receipttransaction_feepayment_receipt_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='applicable_to_subsequent_years',
            field=models.BooleanField(default=False, help_text='If this is an Admission Time Fee, should it also be charged in the 2nd year onwards? (e.g. Exam Fee, Program Fee)'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='fee_type',
            field=models.CharField(choices=[('admission', 'Admission Time Fee'), ('course', 'Course Fee (Yearly)'), ('hostel', 'Hostel Fee (Monthly)'), ('bus', 'Bus Fee (Monthly)'), ('medical', 'Medical Fee (Ad-hoc)'), ('caution', 'Caution Deposit (One-time)'), ('other', 'Other')], default='course', help_text='Classifies the fee for automated workflows and display logic.', max_length=20),
        ),
    ]
