# Generated by Django 5.2.8 on 2026-06-10 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_feeitem_applicable_to_subsequent_years_and_more'),
        ('students', '0028_student_uses_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CautionDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_collected', models.DateField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('is_refunded', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caution_deposits', to='students.student')),
            ],
            options={
                'ordering': ['-date_collected'],
            },
        ),
        migrations.CreateModel(
            name='CautionDepositRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateField(default=django.utils.timezone.now)),
                ('processed_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='fees.cautiondeposit')),
            ],
        ),
    ]
