# Generated by Django 5.2.4 on 2026-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_cautiondeposit_cautiondepositrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Custom name for ad-hoc or custom student fees', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='billing_month',
            field=models.DateField(blank=True, help_text='The month this recurring fee covers (1st of month)', null=True),
        ),
    ]
