# Generated by Django 5.2.4 on 2026-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_studentfee_custom_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default="Markaz Hadiya Women's College", max_length=150)),
                ('account_holder_name', models.CharField(blank=True, help_text='Beneficiary Name', max_length=150)),
                ('bank_name', models.CharField(blank=True, help_text='e.g. State Bank of India, Federal Bank', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Bank Account Number', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC Code', max_length=30)),
                ('branch_name', models.CharField(blank=True, help_text='Branch Name', max_length=100)),
                ('account_type', models.CharField(blank=True, default='Current Account', max_length=50)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID / VPA (e.g. markazhadiya@sbi)', max_length=100)),
                ('upi_number', models.CharField(blank=True, help_text='GPay / PhonePe Mobile Number', max_length=30)),
                ('qr_code_image', models.ImageField(blank=True, help_text='Upload official UPI QR code image', null=True, upload_to='fee_qr_codes/')),
                ('payment_instructions', models.TextField(blank=True, default='1. Pay using any UPI app (GPay, PhonePe, Paytm) or Bank Transfer.\n2. In payment remarks/notes, mention Student Name & Admission ID.\n3. Send payment screenshot to the college accounts desk.')),
                ('helpline_phone', models.CharField(blank=True, default='9947924613', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution Payment Setting',
                'verbose_name_plural': 'Institution Payment Settings',
            },
        ),
    ]
