# Generated by Django 5.2.8 on 2026-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('madrasa', models.CharField(max_length=255)),
                ('student_class', models.CharField(max_length=50)),
                ('board', models.CharField(choices=[('SK SVB', 'Samastha Kerala Sunni Vidyabhyasa Board'), ('SK IMVB', 'Samastha Kerala Islam Matha Vidyabhyasa Board')], max_length=10)),
                ('grade', models.CharField(choices=[('TOP_PLUS', 'Top Plus'), ('DISTINCTION', 'Distinction')], max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
