# Generated by Django 5.2.8 on 2026-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_awazegcampcandidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='madrasa',
            new_name='madrasa_and_place',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='grade',
            field=models.CharField(choices=[('TOPPER', 'Topper'), ('TOP_PLUS', 'Top Plus'), ('DISTINCTION', 'Distinction')], max_length=15),
        ),
    ]
